version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./final_models:/app/final_models
    ports:
      - "8001:8001"
    networks:
      - app-network
    restart: unless-stopped
    container_name: backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    container_name: frontend

networks:
  app-network:
    driver: bridge 